### ISSUE TITLE
Form submission error message "Your request URL is too long."

### ISSUE THREAD

**Issue by smarkowski** [badging/event-diversity-and-inclusion#99] opened 2021-09-16 16:23 UTC
Hello - 

I am the Event Manager for Open Networking & Edge Summit + Kubernetes on Edge Day at the Linux Foundation and we've been trying to submit to the event diversity and inclusion badge form, but keep running into the error message "Your request URL is too long." when we hit submit on the form. This is a virtual event happening October 11-12, 2021. I tried shortening all our URL's in case that was the issue but am still receiving an error.
Is anyone available to help us get this info submitted? If it helps for the review, we've copied all the form responses to a doc here: https://docs.google.com/document/d/1aZhiXrncNBSHcxXcuX8MAtBF0sWWXVQcOPVzqFEL3GU/edit?usp=sharing

My colleague reached out with a similar issue for Open Source Summit - thank you so much for your help with this!
Stephanie

**Comment by Nebrethar** [comment] 2021-09-16 16:40
Hi @smarkowski and welcome! It looks like we will need to fix this error quickly :)

I can go ahead and get the review process started by posting the application on behalf of you and your event. From that point on the review can be carried out as normal - I would also mention that you are the applicant. Would you like me to do that?

**Comment by smarkowski** [comment] 2021-09-16 16:42
Thank you so much - that's perfect!

**Comment by Nebrethar** [comment] 2021-09-16 17:00
Hi again @smarkowski 😁 I am converting the application to markdown, but I noticed that the content of the google doc you shared does not include the Family Friendliness metric. I want to check - is that something you plan to include?

**Comment by smarkowski** [comment] 2021-09-16 17:05
Hi! That section was not included on the application for virtual events.

**Comment by Nebrethar** [comment] 2021-09-16 17:50
Oh - Got it! Sorry about that. I will adjust accordingly

**Comment by Nebrethar** [comment] 2021-09-21 14:49
I am going to close this issue because the problem is now being tracked in #100 . I have a temporary solution in place 🎉 and I'm working on a better implementation.

**Closed by Nebrethar** 2021-09-21 14:49 UTC
