### ISSUE TITLE
Form submission error message "Your request URL is too long."

### ISSUE THREAD

**Issue by creyjons** [badging/event-diversity-and-inclusion#97] opened 2021-09-14 16:21 UTC
Hey all, 

I work on Open Source Summit at the Linux Foundation and we've been trying to submit to the event diversity and inclusion badge form but keep running into the error message "Your request URL is too long." when we hit submit on the form.  I tried shortening all our URL's in case that was the issue but no luck. 

Is anyone available to help us get this info submitted?  If it helps for the review we've copied all the form responses to a doc here: https://docs.google.com/document/d/1ucXWsIWuw4d66rPa99POzwkLpqySZIHyofsM1c5YY_M/edit?usp=sharing

Greatly appreciate any help!

Thanks,
Cassandra

**Comment by Nebrethar** [comment] 2021-09-14 16:28
Hi @creyjons! Thanks for reaching out! It means a lot to me that you are still making an effort to apply. Looks like you found a new bug!

This may take a while to fix. I can go ahead and get this into the correct format and post it verbatim, on behalf of your event. You will still get full credit and the event will be reviewed with the same process. Is that OK?

**Comment by creyjons** [comment] 2021-09-14 18:13
Hi @Nebrethar! Feel free to post on our behalf!  Thanks for the quick reply!  Let me know if you need anything else!

**Comment by Nebrethar** [comment] 2021-09-14 18:22
Sounds good. I have opened issue #98 for you with the information you provided. Thank you for your flexibility. I will keep this issue open until I've solved that bug - should be fixed by Thursday.

**Comment by creyjons** [comment] 2021-09-14 18:22
Thanks for your help @Nebrethar !

**Comment by Nebrethar** [comment] 2021-09-21 14:49
I am going to close this issue because the problem is now being tracked in #100 . I have a temporary solution in place 🎉 and I'm working on a better implementation.

**Closed by Nebrethar** 2021-09-21 14:49 UTC
